// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI1rrhn28zmwR3zV3Bi7IUX6WhD--G7tA',
    appId: '1:331779848326:web:c0358a6ba4363522683907',
    messagingSenderId: '331779848326',
    projectId: 'glowchatwp',
    authDomain: 'glowchatwp.firebaseapp.com',
    storageBucket: 'glowchatwp.appspot.com',
    measurementId: 'G-GVLLXN2GC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqKZhuP7c-xi5LhcBgr9NDz9dKN6na08I',
    appId: '1:331779848326:android:1bbf839343d5f03d683907',
    messagingSenderId: '331779848326',
    projectId: 'glowchatwp',
    storageBucket: 'glowchatwp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVWoAXBYSVUui6o0oNldlF6_1sxOKtJvc',
    appId: '1:331779848326:ios:cfc9b5165b3cd55c683907',
    messagingSenderId: '331779848326',
    projectId: 'glowchatwp',
    storageBucket: 'glowchatwp.appspot.com',
    iosClientId: '331779848326-t3jtdrli50hi3pmqhemmbojlvalu80k9.apps.googleusercontent.com',
    iosBundleId: 'com.valizadarustam.myglow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVWoAXBYSVUui6o0oNldlF6_1sxOKtJvc',
    appId: '1:331779848326:ios:cfc9b5165b3cd55c683907',
    messagingSenderId: '331779848326',
    projectId: 'glowchatwp',
    storageBucket: 'glowchatwp.appspot.com',
    iosClientId: '331779848326-t3jtdrli50hi3pmqhemmbojlvalu80k9.apps.googleusercontent.com',
    iosBundleId: 'com.valizadarustam.myglow',
  );
}
